Lab4_App_Reservation/Models/ReservationModels/Reservation.cs
using Lab4_App_Reservation.Models.ContactModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Lab4_App_Reservation.Models.ReservationModels;

public class Reservation
{
    [HiddenInput]
    public int Id { get; set; }

    [Required(ErrorMessage = "Pole 'Data' jest wymagane.")]
    [Display(Name = "Data")]
    [DataType(DataType.Date)]
    public DateTime Data { get; set; }

    [Required(ErrorMessage = "Pole 'Miasto' jest wymagane.")]
    [Display(Name = "Miasto")]
    public string Miasto { get; set; }

    [Required(ErrorMessage = "Pole 'Adres' jest wymagane.")]
    [Display(Name = "Adres")]
    public string Adress { get; set; }

    [Required(ErrorMessage = "Pole 'Nazwa pokoju' jest wymagane.")]
    [Display(Name = "Nazwa pokoju")]
    public string PokojNazwa { get; set; }

    [Required(ErrorMessage = "Pole 'Numer pokoju' jest wymagane.")]
    [Display(Name = "Numer pokoju")]
    public string PokojNumer { get; set; }

    [Required(ErrorMessage = "Pole 'Rozmiar pokoju' jest wymagane.")]
    [Display(Name = "Rozmiar pokoju")]
    public int PokojRozmiar { get; set; }

    [Required(ErrorMessage = "Pole 'Pietro pokoju' jest wymagane.")]
    [Display(Name = "Pietro pokoju")]
    public int PokojPietro { get; set; }

    [Required(ErrorMessage = "Pole 'Cena' jest wymagane.")]
    [Range(0, double.MaxValue, ErrorMessage = "Cena musi być liczbą nieujemną.")]
    [Display(Name = "Cena")]
    public decimal Cena { get; set; }

    [Display(Name = "Właściciel")]
    public int ContactId { get; set; }
    public string ContactName { get; set; }


    [ValidateNever]
    public List<SelectListItem> ContactList { get; set; }
}

Lab4_App_Reservation/Controllers/ContactController.cs
using Lab4_App_Reservation.Models.ContactModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.RegularExpressions;
using static System.Net.Mime.MediaTypeNames;

namespace Lab4_App_Reservation.Controllers
{
    [Authorize(Roles = "admin")]
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;

        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var contacts = await _contactService.FindAllAsync();
            return View(contacts);
        }

        [AllowAnonymous]
        public async Task<IActionResult> PagedIndex(int page = 1, int size = 5)
        {
            if (size < 1)
            {
                return BadRequest();
            }

            var contactsPaged = await _contactService.FindPageAsync(page, size);
            return View(contactsPaged);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var organizations = CreateOrganizationItemList();
            var model = new Contact { OrganizationList = organizations };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Contact model)
        {
            if (ModelState.IsValid)
            {
                await _contactService.AddAsync(model);
                return RedirectToAction("Index");
            }

            model.OrganizationList = CreateOrganizationItemList();
            return View(model);
        }

        private List<SelectListItem> CreateOrganizationItemList()
        {
            var group = new SelectListGroup { Name = "Organizacje" };
            return _contactService.FindAllOrganizationsAsync()
                .Result 
                .Select(e => new SelectListItem { Text = e.Name, Value = e.Id.ToString(), Group = group })
                .Append(new SelectListItem { Text = "Brak organizacji", Value = "", Selected = true, Group = new SelectListGroup { Name = "Brak" } })
                .ToList();
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var model = await _contactService.FindByIdAsync(id);
            model.OrganizationList = CreateOrganizationItemList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Contact model)
        {
            if (ModelState.IsValid)
            {
                await _contactService.UpdateAsync(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _contactService.FindByIdAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Contact model)
        {
            await _contactService.DeleteByIdAsync(model.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var model = await _contactService.FindByIdAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Details(Contact model)
        {
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CreateApi()
        {

            return View();
        }

        [HttpPost]
        public IActionResult CreateApi(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contactService.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Lab4_App_Reservation/Controllers/ReservationController.cs
using Lab4_App_Reservation.Models.ReservationModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Newtonsoft.Json;

namespace Lab4_App_Reservation.Controllers
{
    [Authorize(Roles = "admin")]

    public class ReservationController : Controller
    {
        private readonly IReservationService _reservationService;

        public ReservationController(IReservationService reservationService)
        {
            _reservationService = reservationService;
        }
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Index(string sortOrder)
        {
            var reservations = await _reservationService.FindAllAsync();

            reservations = SortReservations(reservations, sortOrder);

            ViewBag.CurrentSort = sortOrder;

            return View(reservations);
        }
        private List<Reservation> SortReservations(List<Reservation> reservations, string sortOrder)
        {
            switch (sortOrder)
            {
                case "ContactId_asc":
                    reservations = reservations.OrderBy(r => r.ContactName).ToList();
                    break;
                case "ContactId_desc":
                    reservations = reservations.OrderByDescending(r => r.ContactName).ToList();
                    break;
                case "Miasto_asc":
                    reservations = reservations.OrderBy(r => r.Miasto).ToList();
                    break;
                case "Miasto_desc":
                    reservations = reservations.OrderByDescending(r => r.Miasto).ToList();
                    break;
                case "Data_asc":
                    reservations = reservations.OrderBy(r => r.Data).ToList();
                    break;
                case "Data_desc":
                    reservations = reservations.OrderByDescending(r => r.Data).ToList();
                    break;
                default:
                    reservations = reservations.OrderBy(r => r.ContactId).ToList();
                    break;
            }

            return reservations;
        }

        [HttpGet]
        public async Task<IActionResult> SearchIndexApi(string? search = null)
        {
            try
            {
                List<Reservation> reservations;

                using (var httpClient = new HttpClient())
                {
                    httpClient.BaseAddress = new Uri("https://localhost:7149/");
                    var response = await httpClient.GetAsync($"api/reservations?q={search}");

                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        reservations = JsonConvert.DeserializeObject<List<Reservation>>(content);
                    }
                    else
                    {
                        reservations = new List<Reservation>();
                    }
                }

                ViewBag.SearchTerm = !string.IsNullOrEmpty(search) ? search : null;

                return View(reservations);
            }
            catch (Exception)
            {
                ViewBag.SearchTerm = null;
                return View(new List<Reservation>());
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> PagedIndex(int page = 1, int size = 5)
        {
            if (size < 1)
            {
                return BadRequest();
            }
            return View(await _reservationService.FindPageAsync(page, size));
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var contacts = CreateContactItemList();
            var model = new Reservation { ContactList = contacts };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Reservation model)
        {
            if (ModelState.IsValid)
            {
                await _reservationService.AddAsync(model);
                return RedirectToAction("Index");
            }
            model.ContactList = CreateContactItemList();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var model = await _reservationService.FindByIdAsync(id);
            model.ContactList = CreateContactItemList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Reservation model)
        {
            if (ModelState.IsValid)
            {
                await _reservationService.UpdateAsync(model);
                return RedirectToAction("Index");
            }
            model.ContactList = CreateContactItemList();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _reservationService.FindByIdAsync(id);
            model.ContactList = CreateContactItemList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Reservation model)
        {
            await _reservationService.DeleteByIdAsync(model.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            return View(await _reservationService.FindByIdAsync(id));
        }

        private List<SelectListItem> CreateContactItemList()
        {
            var group = new SelectListGroup { Name = "Kontakty" };
            return _reservationService.FindAllContactsAsync()
                .Result
                .Select(e => new SelectListItem { Text = e.Name, Value = e.ContactId.ToString(), Group = group })
                .ToList();
        }

    }
}

Lab4_App_Reservation/Views/Reservation/Create.cshtml
@using Lab4_App_Reservation.Models.ReservationModels;
@model Reservation


<form class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md" asp-controller="Reservation" asp-action="Create" method="post">
    <h1 class="text-3xl font-bold mb-4 text-center">Dodaj rezerwację</h1>
    <a asp-controller="Reservation" asp-action="Index" class="text-blue-500 text-lg hover:underline flex items-center mb-4">
        <svg class="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
        </svg>
        Powrót
    </a>
    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="Data"></label>
            <input class="form-input border rounded-md p-2" asp-for="Data" />
        <span class="text-red-500 text-xs" asp-validation-for="Data"></span>
    </div>
    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="Miasto"></label>
            <input class="form-input border rounded-md p-2" asp-for="Miasto" />
        <span class="text-red-500 text-xs" asp-validation-for="Miasto"></span>
    </div>

    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="Adress"></label>
            <input class="form-input border rounded-md p-2" asp-for="Adress" />
        <span class="text-red-500 text-xs" asp-validation-for="Adress"></span>
    </div>

    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="PokojNumer"></label>
            <input class="form-input border rounded-md p-2 border rounded-md p-2" asp-for="PokojNumer" />
        <span class="text-red-500 text-xs" asp-validation-for="PokojNumer"></span>
    </div>

    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="PokojNazwa"></label>
            <input class="form-input border rounded-md p-2" asp-for="PokojNazwa" />
        <span class="text-red-500 text-xs" asp-validation-for="PokojNazwa"></span>
    </div>

    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="PokojPietro"></label>
            <input class="form-input  border rounded-md p-2" asp-for="PokojPietro" />
        <span class="text-red-500 text-xs" asp-validation-for="PokojPietro"></span>
    </div>

    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="PokojRozmiar"></label>
            <input class="form-input border rounded-md p-2" asp-for="PokojRozmiar" />
        <span class="text-red-500 text-xs" asp-validation-for="PokojRozmiar"></span>
    </div>

    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="ContactId"></label>
            <select class="form-select border rounded-md p-2" asp-for="ContactId" asp-items="@Model.ContactList"></select>
        <a class="text-blue-500 text-sm hover:underline" asp-controller="Contact" asp-action="Create">Utworz Contact</a>
    </div>

    <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="Cena"></label>
            <input class="form-input  border rounded-md p-2" asp-for="Cena" />
        <span class="text-red-500 text-xs" asp-validation-for="Cena"></span>
    </div>

    <div class="mb-4">
        <button class="bg-blue-500 text-white py-2 px-4 rounded-full hover:bg-blue-700" type="submit">Utwórz</button>
    </div>

    <div class="mb-4">
        <input type="hidden" class="form-input" asp-for="ContactName" id="ContactName" />
    </div>
</form>


@section scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var contactIdSelect = document.getElementById('ContactId');
            var contactNameInput = document.getElementById('ContactName');

            contactIdSelect.addEventListener('change', function () {
                var selectedContactId = this.value;

                var selectedContact = @Html.Raw(Json.Serialize(Model.ContactList))
                            .find(contact => contact.value == selectedContactId);

                contactNameInput.value = selectedContact.text;
            });
        });
    </script>
}

Lab4_App_Reservation/Views/Reservation/Delete.cshtml
@using Lab4_App_Reservation.Models.ReservationModels;
@model Reservation

<div class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md">
    <h1 class="text-3xl font-bold mb-4">
        Czy na pewno chcesz usunąć rezerwację?
    </h1>
    <div class="mb-2">
        <h3 class="text-lg font-semibold">Właściciel: @Model.ContactName</h3>
    </div>
    <div class="mb-2">
        <h3 class="text-lg font-semibold">Data: @Model.Data.ToShortDateString()</h3>
    </div>
    <div class="mb-2">
        <h3 class="text-lg font-semibold">Miasto: @Model.Miasto</h3>
    </div>

    <form asp-action="Delete" method="post" class="mb-4">
        <input asp-for="Id" type="hidden" />
        <button class="bg-red-500 text-white py-2 px-4 rounded-full hover:bg-red-700 mr-2" type="submit">Tak</button>
        <a class="bg-gray-500 text-white py-2 px-4 rounded-full hover:bg-gray-700" asp-action="Index">Nie</a>
    </form>
</div>

Lab4_App_Reservation/Views/Reservation/Index.cshtml
@using Lab4_App_Reservation.Models;
@using Lab4_App_Reservation.Models.ReservationModels;

@model List<Reservation>


<h1 class="text-2xl font-bold mb-4">Lista rezerwacji</h1>
<a class="bg-blue-500 text-white px-4 py-2 rounded inline-block mb-4 hover:bg-blue-700" asp-controller="Reservation" asp-action="Create">Utwórz rezerwacje</a>
<a class="bg-blue-500 text-white px-4 py-2 rounded inline-block mb-4 hover:bg-blue-700" asp-controller="Reservation" asp-action="PagedIndex">Stronicowana witryna</a>
<a class="bg-blue-500 text-white px-4 py-2 rounded inline-block mb-4 hover:bg-blue-700" asp-controller="Reservation" asp-action="SearchIndexApi">Wyszukiwarka Właściciela API</a>


@if (Model.Count > 0)
{
    <table class="min-w-full bg-white border border-gray-300">
        <thead class="bg-gray-100">
            <tr>
                <th class="py-2 px-4 border-b">
                    <a href="@Url.Action("Index", new { sortOrder = ViewBag.CurrentSort == "ContactId_asc" ? "ContactId_desc" : "ContactId_asc" })" class="underline text-blue-500 hover:text-blue-700">
                        <span>@Html.DisplayNameFor(i => Model[0].ContactId)</span>
                        <span class="sort-arrow @(ViewBag.CurrentSort == "ContactId_asc" ? "up" : (ViewBag.CurrentSort == "ContactId_desc" ? "down" : ""))"></span>
                    </a>
                </th>
                <th class="py-2 px-4 border-b">
                    <a href="@Url.Action("Index", new { sortOrder = ViewBag.CurrentSort == "Miasto_asc" ? "Miasto_desc" : "Miasto_asc" })" class="underline text-blue-500 hover:text-blue-700">
                        
                        <span>@Html.DisplayNameFor(i => Model[0].Miasto)</span>
                        <span class="sort-arrow @(ViewBag.CurrentSort == "Miasto_asc" ? "up" : (ViewBag.CurrentSort == "Miasto_desc" ? "down" : ""))"></span>
                    </a>
                </th>
                <th class="py-2 px-4 border-b">
                    <a href="@Url.Action("Index", new { sortOrder = ViewBag.CurrentSort == "Data_asc" ? "Data_desc" : "Data_asc" })" class="underline text-blue-500 hover:text-blue-700">
                       
                        <span>@Html.DisplayNameFor(i => Model[0].Data)</span>
                        <span class="sort-arrow @(ViewBag.CurrentSort == "Data_asc" ? "up" : (ViewBag.CurrentSort == "Data_desc" ? "down" : ""))"></span>
                    </a>
                </th>

                <th class="py-2 px-4 border-b">
                    <a href="@Url.Action("Index", new { sortOrder = ViewBag.CurrentSort == "PokojNazwa_asc" ? "PokojNazwa_desc" : "PokojNazwa_asc" })" class="underline text-blue-500 hover:text-blue-700">

                        <span>@Html.DisplayNameFor(i => Model[0].PokojNazwa)</span>
                        <span class="sort-arrow @(ViewBag.CurrentSort == "PokojNazwa_asc" ? "up" : (ViewBag.CurrentSort == "PokojNazwa_desc" ? "down" : ""))"></span>
                    </a>
                </th>
            </tr>
        </thead>


        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="py-2 px-4 border-b">
                        @item.ContactName
                    </td>
                    <td class="py-2 px-4 border-b">
                        @item.Miasto
                    </td>
                    <td class="py-2 px-4 border-b">
                        @item.Data.ToShortDateString()
                    </td>
                    <td class="py-2 px-4 border-b">
                        @item.PokojNazwa
                    </td>
                    
                    <td class="py-2 px-4 border-b">
                        <a class="bg-blue-500 text-white px-4 py-2 rounded mr-2 hover:bg-blue-700" asp-controller="Reservation" asp-action="Update" asp-route-id="@item.Id">Edytuj</a>
                        <a class="bg-green-500 text-white px-4 py-2 rounded mr-2 hover:bg-green-700" asp-controller="Reservation" asp-action="Details" asp-route-id="@item.Id">Szczególy</a>
                        <a class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-700" asp-controller="Reservation" asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p class="mt-4">Nie znaleziono rezerwacji.</p>
}

Lab4_App_Reservation/Views/Reservation/PagedIndex.cshtml
@using Lab4_App_Reservation.Models;
@using Lab4_App_Reservation.Models.ReservationModels;

@model PagingList<Reservation>

<h1 class="text-2xl font-bold mb-4">Lista rezerwacji</h1>
<a class="bg-blue-500 text-white px-4 py-2 rounded inline-block mb-4 hover:bg-blue-700" asp-controller="Reservation" asp-action="Create">Utwórz rezerwację</a>
<a class="bg-blue-500 text-white px-4 py-2 rounded inline-block mb-4 hover:bg-blue-700" asp-controller="Reservation" asp-action="Index">Zwykła witryna</a>
<a class="bg-blue-500 text-white px-4 py-2 rounded inline-block mb-4 hover:bg-blue-700" asp-controller="Reservation" asp-action="SearchIndexApi">Wyszukiwarka Właściciela API</a>




@if (Model.Data.Count() > 0)
{
    <table class="min-w-full bg-white border border-gray-300 mt-4">
        <thead>
            <tr>
                <th class="py-2 px-4 border-b">
                    @Html.DisplayNameFor(model => model.Data.GetEnumerator().Current.ContactId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Data.GetEnumerator().Current.Miasto)
                </th class="py-2 px-4 border-b">
                <th>
                    @Html.DisplayNameFor(model => model.Data.GetEnumerator().Current.Data)
                </th>
                <th class="py-2 px-4 border-b">
                    Akcje
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td class="py-2 px-4 border-b">
                        @item.ContactName
                    </td>
                    <td class="py-2 px-4 border-b">
                        @item.Miasto
                    </td>
                    <td class="py-2 px-4 border-b">
                        @item.Data.ToShortDateString()
                    </td>
                    <td class="py-2 px-4 border-b">
                        <a class="bg-blue-500 text-white px-4 py-2 rounded mr-2 hover:bg-blue-700" asp-controller="Reservation" asp-action="Update" asp-route-id="@item.Id">Edytuj</a>
                        <a class="bg-green-500 text-white px-4 py-2 rounded mr-2 hover:bg-green-700" asp-controller="Reservation" asp-action="Details" asp-route-id="@item.Id">Szczegóły</a>
                        <a class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-700" asp-controller="Reservation" asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p class="mt-4">Nie znaleziono rezerwacji.</p>
}

<nav aria-label="Books page navigation" class="mt-4">
    <ul class="pagination">
        @if (Model.IsPrevious)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-controller="Reservation"
                   asp-action="PagedIndex"
                   asp-route-page="@(Model.Page - 1)"
                   asp-route-size="@Model.Size">
                    Poprzednia
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link">Poprzednia</a>
            </li>
        }
        <li class="page-item disabled">
            <a class="page-link">@Model.Page</a>
        </li>
        @if (Model.IsNext)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-controller="Reservation"
                   asp-action="PagedIndex"
                   asp-route-page="@(Model.Page + 1)"
                   asp-route-size="@Model.Size">
                    Następna
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link">Następna</a>
            </li>
        }
    </ul>
</nav>

Lab4_App_Reservation/Views/Reservation/Update.cshtml
@using Lab4_App_Reservation.Models.ReservationModels;
@model Reservation

    <form class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md" asp-controller="Reservation" asp-action="Create" method="post">
        <h1 class="text-3xl font-bold mb-4 text-center">Edytuj rezerwację</h1>
        <a asp-controller="Reservation" asp-action="Index" class="text-blue-500 text-lg hover:underline flex items-center mb-4">
        <svg class="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
        </svg>
        Powrót
        </a>
        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="Data"></label>
            <input class="form-input border rounded-md p-2" asp-for="Data" />
            <span class="text-red-500 text-xs" asp-validation-for="Data"></span>
        </div>
        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="Miasto"></label>
            <input class="form-input border rounded-md p-2" asp-for="Miasto" />
            <span class="text-red-500 text-xs" asp-validation-for="Miasto"></span>
        </div>

        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="Adress"></label>
            <input class="form-input border rounded-md p-2" asp-for="Adress" />
            <span class="text-red-500 text-xs" asp-validation-for="Adress"></span>
        </div>

        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="PokojNumer"></label>
            <input class="form-input border rounded-md p-2 border rounded-md p-2" asp-for="PokojNumer" />
            <span class="text-red-500 text-xs" asp-validation-for="PokojNumer"></span>
        </div>

        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="PokojNazwa"></label>
            <input class="form-input border rounded-md p-2" asp-for="PokojNazwa" />
            <span class="text-red-500 text-xs" asp-validation-for="PokojNazwa"></span>
        </div>

        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="PokojPietro"></label>
            <input class="form-input  border rounded-md p-2" asp-for="PokojPietro" />
            <span class="text-red-500 text-xs" asp-validation-for="PokojPietro"></span>
        </div>

        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="PokojRozmiar"></label>
            <input class="form-input border rounded-md p-2" asp-for="PokojRozmiar" />
            <span class="text-red-500 text-xs" asp-validation-for="PokojRozmiar"></span>
        </div>

        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="ContactId"></label>
            <select class="form-select border rounded-md p-2" asp-for="ContactId" asp-items="@Model.ContactList"></select>
            <a class="text-blue-500 text-sm hover:underline" asp-controller="Contact" asp-action="Create">Utworz Contact</a>
        </div>

        <div class="mb-4">
            <label class="text-lg font-semibold" asp-for="Cena"></label>
            <input class="form-input  border rounded-md p-2" asp-for="Cena" />
            <span class="text-red-500 text-xs" asp-validation-for="Cena"></span>
        </div>

        <div class="mb-4">
            <button class="bg-blue-500 text-white py-2 px-4 rounded-full hover:bg-blue-700" type="submit">Zapisz</button>
        </div>

        <div class="mb-4">
            <input type="hidden" class="form-input" asp-for="ContactName" id="ContactName" />
        </div>
    </form>



@section scripts {
    <script>
        $(document).ready(function () {
            $('#ContactId').change(function () {
                var selectedContactId = $(this).val();

                var selectedContact = @Html.Raw(Json.Serialize(Model.ContactList))
                    .find(contact => contact.value == selectedContactId);

                $('#ContactName').val(selectedContact.text);
            });
        });
    </script>
}